git:
  depth: 5

jobs:
  include:
    - stage : "Build and Test Java"
      language: Java
      jdk: oraclejdk11
      before script:
        - cd sample-application-backend 
    - stage : "Build and Test Nodejs"
      language: node.js
      node_js: "12.20"
      before script:
        - cd sample-application-frontend 

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.npm"