git:
  depth: 5

stage:
  - "Build and Test"
  - "Package"

jobs:
  include:
    - stage : "Build and Test"
      language: Java
      jdk: oraclejdk11
      before script:
        - cd sample-application-backend 
      script:
        - mvn package
        - mvn test -B
        - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=adrienCrosio_sample-application-students

    - stage : "Build and Test"
      language: node.js
      node_js: "12.20"
      -script:
        - npm install
        - npm run test
      before script:
        - cd sample-application-frontend 

    - stage: "Package"
      before script:
        - cd sample-application-frontend
      script:
        - docker build -t diomedex/sample-app-front .
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker push diomedex/sample-app-front

    - stage: "Package"
      before script:
        - cd sample-application-backend
      script:
        - docker build -t diomedex/sample-app-back .
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker push diomedex/sample-app-back

services:
  - docker
  
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.npm"

addons:
  sonarcloud:
    organization: "adrienCrosio"
    token: "$SONARCLOUD_TOKEN"