git:
  depth: 5

stages:
  - name: Build and Test
    if: branch = master
  - name: Package
    if: branch = master

addons:
  sonarcloud:
    organization: "adriencrosio"
    token: "$SONARCLOUD_TOKEN"

jobs:
  include:
    - stage : "Build and Test"
      language: Java
      jdk: oraclejdk11
      before script:
        - cd sample-application-backend 
      script:
        - mvn clean
        - mvn verify
        - mvn org.jacoco:jacoco-maven-plugin:prepare-agent
        - mvn sonar:sonar -Dsonar.projectKey=adrienCrosio_sample-application-students

    - stage : "Build and Test"
      language: node.js
      node_js: "12.20"
      -script:
        - npm install
        - npm run test
      before script:
        - cd sample-application-frontend 

    - stage: "Package"
      before script:
        - cd sample-application-frontend
      script:
        - docker build -t $DOCKER_USERNAME/sample-app-front .
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker push $DOCKER_USERNAME/sample-app-front

    - stage: "Package"
      before script:
        - cd sample-application-backend
      script:
        - docker build -t $DOCKER_USERNAME/sample-app-back .
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker push $DOCKER_USERNAME/sample-app-back

services:
  - docker
  
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.npm"